/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppConnectRouteImport } from './routes/app/connect'
import { Route as AppPipelineIndexRouteImport } from './routes/app/pipeline/index'
import { Route as AppInboxIndexRouteImport } from './routes/app/inbox/index'
import { Route as AppDashboardIndexRouteImport } from './routes/app/dashboard/index'
import { Route as AppSettingsTeamRouteImport } from './routes/app/settings/team'
import { Route as AppSettingsPipelineRouteImport } from './routes/app/settings/pipeline'
import { Route as AppInboxConversationIdRouteImport } from './routes/app/inbox/$conversationId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppConnectRoute = AppConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineIndexRoute = AppPipelineIndexRouteImport.update({
  id: '/pipeline/',
  path: '/pipeline/',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxIndexRoute = AppInboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsTeamRoute = AppSettingsTeamRouteImport.update({
  id: '/settings/team',
  path: '/settings/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsPipelineRoute = AppSettingsPipelineRouteImport.update({
  id: '/settings/pipeline',
  path: '/settings/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxConversationIdRoute = AppInboxConversationIdRouteImport.update({
  id: '/inbox/$conversationId',
  path: '/inbox/$conversationId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/connect': typeof AppConnectRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/': typeof AppIndexRoute
  '/app/inbox/$conversationId': typeof AppInboxConversationIdRoute
  '/app/settings/pipeline': typeof AppSettingsPipelineRoute
  '/app/settings/team': typeof AppSettingsTeamRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
  '/app/inbox/': typeof AppInboxIndexRoute
  '/app/pipeline/': typeof AppPipelineIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/app/connect': typeof AppConnectRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app': typeof AppIndexRoute
  '/app/inbox/$conversationId': typeof AppInboxConversationIdRoute
  '/app/settings/pipeline': typeof AppSettingsPipelineRoute
  '/app/settings/team': typeof AppSettingsTeamRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
  '/app/inbox': typeof AppInboxIndexRoute
  '/app/pipeline': typeof AppPipelineIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/connect': typeof AppConnectRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/': typeof AppIndexRoute
  '/app/inbox/$conversationId': typeof AppInboxConversationIdRoute
  '/app/settings/pipeline': typeof AppSettingsPipelineRoute
  '/app/settings/team': typeof AppSettingsTeamRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
  '/app/inbox/': typeof AppInboxIndexRoute
  '/app/pipeline/': typeof AppPipelineIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/connect'
    | '/auth/login'
    | '/auth/register'
    | '/app/'
    | '/app/inbox/$conversationId'
    | '/app/settings/pipeline'
    | '/app/settings/team'
    | '/app/dashboard/'
    | '/app/inbox/'
    | '/app/pipeline/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/connect'
    | '/auth/login'
    | '/auth/register'
    | '/app'
    | '/app/inbox/$conversationId'
    | '/app/settings/pipeline'
    | '/app/settings/team'
    | '/app/dashboard'
    | '/app/inbox'
    | '/app/pipeline'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/connect'
    | '/auth/login'
    | '/auth/register'
    | '/app/'
    | '/app/inbox/$conversationId'
    | '/app/settings/pipeline'
    | '/app/settings/team'
    | '/app/dashboard/'
    | '/app/inbox/'
    | '/app/pipeline/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/connect': {
      id: '/app/connect'
      path: '/connect'
      fullPath: '/app/connect'
      preLoaderRoute: typeof AppConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pipeline/': {
      id: '/app/pipeline/'
      path: '/pipeline'
      fullPath: '/app/pipeline/'
      preLoaderRoute: typeof AppPipelineIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox/': {
      id: '/app/inbox/'
      path: '/inbox'
      fullPath: '/app/inbox/'
      preLoaderRoute: typeof AppInboxIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard/': {
      id: '/app/dashboard/'
      path: '/dashboard'
      fullPath: '/app/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/team': {
      id: '/app/settings/team'
      path: '/settings/team'
      fullPath: '/app/settings/team'
      preLoaderRoute: typeof AppSettingsTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/pipeline': {
      id: '/app/settings/pipeline'
      path: '/settings/pipeline'
      fullPath: '/app/settings/pipeline'
      preLoaderRoute: typeof AppSettingsPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox/$conversationId': {
      id: '/app/inbox/$conversationId'
      path: '/inbox/$conversationId'
      fullPath: '/app/inbox/$conversationId'
      preLoaderRoute: typeof AppInboxConversationIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConnectRoute: typeof AppConnectRoute
  AppIndexRoute: typeof AppIndexRoute
  AppInboxConversationIdRoute: typeof AppInboxConversationIdRoute
  AppSettingsPipelineRoute: typeof AppSettingsPipelineRoute
  AppSettingsTeamRoute: typeof AppSettingsTeamRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppInboxIndexRoute: typeof AppInboxIndexRoute
  AppPipelineIndexRoute: typeof AppPipelineIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConnectRoute: AppConnectRoute,
  AppIndexRoute: AppIndexRoute,
  AppInboxConversationIdRoute: AppInboxConversationIdRoute,
  AppSettingsPipelineRoute: AppSettingsPipelineRoute,
  AppSettingsTeamRoute: AppSettingsTeamRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppInboxIndexRoute: AppInboxIndexRoute,
  AppPipelineIndexRoute: AppPipelineIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
